.PHONY: clean All

All:
	@echo "----------Building project:[ Ejemplo_Colas - Debug ]----------"
	@"$(MAKE)" -f  "Ejemplo_Colas.mk"
clean:
	@echo "----------Cleaning project:[ Ejemplo_Colas - Debug ]----------"
	@"$(MAKE)" -f  "Ejemplo_Colas.mk" clean
