.PHONY: clean All

All:
	@echo "----------Building project:[ Ejemplo14 - Debug ]----------"
	@cd "Ejemplo14" && "$(MAKE)" -f  "Ejemplo14.mk"
clean:
	@echo "----------Cleaning project:[ Ejemplo14 - Debug ]----------"
	@cd "Ejemplo14" && "$(MAKE)" -f  "Ejemplo14.mk" clean
